### ISSUE TITLE
php-fpm not starting since 1.5.2-r7-fpm

### ISSUE THREAD

**Issue by waja** [instrumentisto/roundcube-docker-image#11]
Hi,

thanks for keeping up this nice project.

With the update from `1.5.2-r6-fpm` to `1.5.2-r7-fpm` yesterday the image is running but not able to start `php-fpm`.

The process list of the container is:
```
/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
   17 root      0:00 {rc.init} /bin/sh -e /run/s6/basedir/scripts/rc.init top /docker-entrypoint.sh php-fpm
   18 root      0:00 s6-supervise s6-linux-init-shutdownd
   20 root      0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
   22 root      0:00 s6-rc-init -c /run/s6/db /run/service
   23 root      0:13 /package/admin/s6/command/s6-ftrigrd
   24 root      0:00 sh
   29 root      0:00 ps aux
/app #
```

Indeed, there is no log output cause `syslog` is also not running.

Here is the process list of `1.5.2-r6-fpm`:
```
/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
   17 root      0:00 {rc.init} /bin/sh -e /run/s6/basedir/scripts/rc.init top /docker-entrypoint.sh php-fpm
   18 root      0:00 s6-supervise s6-linux-init-shutdownd
   21 root      0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
   24 root      0:00 s6-supervise s6rc-fdholder
   25 root      0:00 s6-supervise syslog
   26 root      0:00 s6-supervise s6rc-oneshot-runner
   33 root      0:00 syslogd -n
   36 root      0:00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-one
   66 root      0:00 php-fpm: master process (/usr/local/etc/php-fpm.conf)
   73 www-data  0:00 php-fpm: pool www
   74 www-data  0:00 php-fpm: pool www
   75 root      0:00 sh
   81 root      0:00 ps aux
/app #
```

If there is anything I can provide to help to trace this issue down, please let me know.

Many thanks, Jan.

**Comment by tyranron** [comment]
@waja this is weird... 🤔   
I cannot reproduce this. Taking the [example](https://github.com/instrumentisto/roundcube-docker-image/blob/1.5.2-r7/examples/fpm-nginx.docker-compose.yml) and adjusting it like this:
```yaml
version: '3'
services:
  roundcube:
    image: ghcr.io/instrumentisto/roundcube:1.5.2-r7-fpm
    expose:
      - "9000"
    volumes:
      - app-volume:/app
      - ./roundcube.config.php:/app/config/config.inc.php:ro
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - roundcube
    ports:
      - "80:80"
    volumes:
      - app-volume:/var/www
      - ./fpm.nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  app-volume:
```
Gives me that everyhing is OK:
```
$ docker compose -f fpm-nginx.docker-compose.yml up       
[+] Running 3/3
 ⠿ Network examples_default        Created                                                                                                    0.2s
 ⠿ Container examples-roundcube-1  Created                                                                                                    0.3s
 ⠿ Container examples-nginx-1      Created                                                                                                    0.3s
Attaching to examples-nginx-1, examples-roundcube-1
examples-roundcube-1  | s6-rc: info: service syslog: starting
examples-roundcube-1  | s6-rc: info: service s6rc-oneshot-runner: starting
examples-roundcube-1  | s6-rc: info: service syslog successfully started
examples-roundcube-1  | Jun 22 14:10:16 c0d8e2adf99b syslog.info syslogd started: BusyBox v1.35.0
examples-roundcube-1  | s6-rc: info: service s6rc-oneshot-runner successfully started
examples-roundcube-1  | s6-rc: info: service fix-attrs: starting
examples-roundcube-1  | s6-rc: info: service fix-attrs successfully started
examples-roundcube-1  | s6-rc: info: service legacy-cont-init: starting
examples-roundcube-1  | s6-rc: info: service legacy-cont-init successfully started
examples-roundcube-1  | s6-rc: info: service legacy-services: starting
examples-roundcube-1  | s6-rc: info: service legacy-services successfully started
examples-roundcube-1  | [22-Jun-2022 14:10:16] STARTUP: PHP OPcache JIT is enabled of 100M
examples-roundcube-1  | [22-Jun-2022 14:10:16 Etc/UTC] PHP Deprecated:  PHP Startup: Use of mbstring.internal_encoding is deprecated in Unknown on line 0
examples-roundcube-1  | [22-Jun-2022 14:10:17] NOTICE: fpm is running, pid 67
examples-roundcube-1  | [22-Jun-2022 14:10:17] NOTICE: ready to handle connections
examples-nginx-1      | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
examples-nginx-1      | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
examples-nginx-1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
examples-nginx-1      | 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
examples-nginx-1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
examples-nginx-1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
examples-nginx-1      | /docker-entrypoint.sh: Configuration complete; ready for start up
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: using the "epoll" event method
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: nginx/1.22.0
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: built by gcc 11.2.1 20220219 (Alpine 11.2.1_git20220219) 
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: OS: Linux 5.10.76-linuxkit
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: start worker processes
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: start worker process 24
examples-nginx-1      | 2022/06/22 14:10:18 [notice] 1#1: start worker process 25
```
<img width="851" alt="Screenshot 2022-06-22 at 16 11 58" src="https://user-images.githubusercontent.com/7114909/175051245-fbbeddae-e31c-49a9-b2a6-9735e0c5e025.png">

**Comment by waja** [comment]
My config is the following and working well with `r6` but not with `r7`:

```
networks:
  system_traefik:
    external: true
    name: system_traefik
services:
  nginx:
    depends_on:
      roundcube:
        condition: service_started
    image: nginx:stable-alpine
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.backend: nginx
      traefik.default.protocol: http
      traefik.docker.network: system_traefik
      traefik.enable: "true"
      traefik.http.routers.roundcube-nginx-itYXUrdajns5.entrypoints: websecure
      traefik.http.routers.roundcube-nginx-itYXUrdajns5.middlewares: default-security-headers@file
      traefik.http.routers.roundcube-nginx-itYXUrdajns5.rule: Host(`webmail.test.org`)
      traefik.http.routers.roundcube-nginx-itYXUrdajns5.tls: "true"
      traefik.http.routers.roundcube-nginx-itYXUrdajns5.tls.certresolver: default
      traefik.http.services.roundcube-nginx-itYXUrdajns5.loadbalancer.server.port: '80'
      traefik.port: '80'
    networks:
      default: {}
      system_traefik: {}
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./config/fpm.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - /etc/timezone:/etc/timezone:ro
    - app-volume:/var/www:rw
  roundcube:
    image: instrumentisto/roundcube:1.5-fpm
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
    - app-volume:/app:rw
    - ./config/roundcube.config.php:/app/config/config.inc.php:ro
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/db:/var/db:rw
version: '3.7'
volumes:
  app-volume: {}
```

Looking at the config of the roundcube container, I don't see something special, which might cause the issue. But since the issue seems related to starting all the processes on container startup I would guess it might be related to https://github.com/instrumentisto/roundcube-docker-image/commit/9f8e6ea0a5aa71981d915f76cde4ebe5acb4d831?
