### ISSUE TITLE
To use MySQL?

### ISSUE THREAD

**Issue by wicadmin** [instrumentisto/roundcube-docker-image#6]
What else change would I need to make to use MySQL as the database? I have the following:

**roundcube.config.php:**

```
<?php
$config = [];
$config['db_dsnw'] = 'mysql://mail:mail@mysql/roundcubemail';
$config['des_key'] = 'somethingsecurehere';
$config['plugins'] = [
    'archive',
    'zipdownload',
];


```
**docker-compose.yml;**

```

version: '3'
services:
  roundcube:
    container_name: roundcube
    restart: unless-stopped
    image: instrumentisto/roundcube:fpm
    expose:
      - "9000"
    depends_on:
      - mysql
    volumes:
      - app-volume:/app
      - ./roundcube.config.php:/app/config/config.inc.php:ro
    environment:
      - ROUNDCUBEMAIL_DB_HOST=roundcube_mysql
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_USER=mail
      - ROUNDCUBEMAIL_DB_PASSWORD=mail
  nginx:
    container_name: roundcube_nginx
    restart: unless-stopped
    image: nginx:stable-alpine
    depends_on:
      - roundcube
    ports:
      - "8550:80"
    volumes:
      - app-volume:/var/www
      - ./fpm.nginx.conf:/etc/nginx/conf.d/default.conf:ro
  mysql:
    image: mysql:5.7
    container_name: roundcube_mysql
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - /home/rancher/myDockers/roundcube-sds/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=roundcubemail
      - MYSQL_USER=mail
      - MYSQL_PASSWORD=mail

volumes:
  app-volume:
```

I am getting error:

```
DATABASE ERROR: CONNECTION FAILED!
Unable to connect to the database!
Please contact your server-administrator.
```
